### PR TITLE
Utaustin ospo blog post

### PR DESCRIPTION
**Pull request by jameshowison**
Adding a blog post about the UT Austin OSPO (discussed by email with @karthik and @kyleniemeyer 

Original source at https://docs.google.com/document/d/14oFhmxNuY-Qf3AaXuxIMdoUW88M1sbm8N23OP99DsSM/edit

Images were put into static folder, and just inserted with basic markdown links.  Ideas on hugo favorable layout welcome!

### CODE REVIEW

**Comment by jameshowison** [comment]
Hmmm.  Seems that image-gallery from here:

uses the $image.Fit command and it is failing.  Perhaps Hugo needs to be updated?  https://gohugo.io/content-management/image-processing/

But other suggestions on images welcome!

**Comment by jameshowison** [comment]
Yeah, futzing with the code in the shortcode shows that the files names are getting to the code, but then having trouble with the Resources and the .Fit and .Fill methods.

**Comment by karthik** [comment]
Here is what your blog post looks like: https://deploy-preview-49--urssi.netlify.app/blog/2024/02/20/a-pathway-for-participation-in-research-open-source/

What do you think? I can make smaller images and link to the full size ones if you're ok with it.

**Comment by jameshowison** [comment]
I was more hoping to get the shortcode image-gallery working, but no worries if that is too much (I think it requires an upgrade of Hugo because it does on-demand image resizing).

There are more images, I can get them into the markdown document so you can see them.  Even smaller I think they are going to take up a lot of vertical space, so I hoped to lay them on top of each other (hence the gallery idea).

I'll quickly play with some older gallery options and see if those work.

**Pull request merged**
