### PR TITLE
Charting the course project

### PR DESCRIPTION
**Pull request by dr-eric-jensen**
This includes the project information added to the projects section of the website. It also includes a small modification to the single.html template to customize the project's page.

### CODE REVIEW

**Comment by karthik** [comment]
Thanks, Eric! Here is the preview of your post: https://urssi.us/blog/2023/06/22/introducing-charting-the-course-policy-and-planning-for-sustainable-research-software/

If this looks good, we can go ahead and merge it.

**Comment by danielskatz** [comment]
This preview is for the blog post that I published/merged last week.

**Comment by karthik** [comment]
Here is the correct one: https://deploy-preview-40--urssi.netlify.app/blog/2023/06/22/introducing-charting-the-course-policy-and-planning-for-sustainable-research-software/

**Comment by karthik** [comment]
I'll fix the relative links so the ones in the deploy preview (last link in the checks above) will link correctly in the previews.

**Comment by dr-eric-jensen** [comment]
Thanks much Karthik!

I look forward to reviewing the website homepage preview when it'savailable.

Best,
Eric

________________________________

**Comment by danielskatz** [comment]
merging - looks ok

**Comment by karthik** [comment]
Do you want to set up a call to talk through this?

**Comment by dr-eric-jensen** [comment]
Dear Karthik,

I set up a Github pages website to show the contents of the Charting the
Course project on the subdomain policy.urssi.us. Now, for the contents to
be available, there are some final steps that need to be performed by the
urssi.us domain admin, so I hope you can add the following to the DNS
configuration:


*1) Add a DNS TXT record*
Create a TXT record in your DNS configuration for the following hostname
(include the underscore at the beginning):
_github-pages-challenge-dr-eric-jensen.policy.urssi.us ***

Use this code for the value of the TXT record:
6712dbdf3459d3064ded509319fa1e


*2) Add a CNAME record using the following values:*
Name: policy
Value: dr-eric-jensen.github.io ***

***Gmail creates hyperlinks automatically as if those parts were URLs, so
please use the text that is displayed instead of the hyperlink.

Please let me know if you need any clarifications.

Best wishes,

Juan Roberto

Operations and Digital Media Analyst

Institute for Methods Innovation (IMI)

***@***.***

www.methodsinnovation.org

<http://www.methodsinnovation.org/>

This message is confidential and may contain privileged information. This
e-mail does not constitute nor form part of a contract or unilateral
obligation. Institute for Methods Innovation does not accept responsibility
for changes made to this message after it was sent.

Institute for Methods Innovation is a registered CIO Foundation with the
Charity Commision in England (Charity No. 1174368) and not-for-profit in
California, USA (C4025842).

**Comment by karthik** [comment]
@dr-eric-jensen Please see my comment above. There are things to discuss before moving stuff to a subdomain. It will likely break all of the rss feeds and turn an institute into separate efforts.  I am available to chat next week.

**Comment by dr-eric-jensen** [comment]
Hi Karthik,

Sounds good, thanks. For meeting timing, which time zone are you in?

Best,
Eric

________________________________

**Pull request merged**
