### PR TITLE
Creates winter school announcement blog post

### PR DESCRIPTION
**Pull request by kyleniemeyer**

### CODE REVIEW

**Comment by karthik** [comment]
Here is the deploy preview (need to update relative links)

https://deploy-preview-47--urssi.netlify.app/blog/2023/10/31/applications-now-open-for-the-2024-urssi-winter-school-in-research-software-engineering/

**Comment by kyleniemeyer** [comment]
Got it- I will also make some formatting changes.

**Comment by kyleniemeyer** [comment]
@karthik does this look good now?

**Comment by karthik** [comment]
LGTM

**Pull request merged**
