### PR TITLE
Create 2023-10-04-new-policy-activities.md

### PR DESCRIPTION
**Pull request by dr-eric-jensen**
Blog post about the GitHub issues for research software policy ideas

### CODE REVIEW

**Comment by danielskatz** [comment]
@karthik - Should we see a draft of this new post in the deploy preview?

**Comment by karthik** [comment]
Yes the preview is there: https://deploy-preview-43--urssi.netlify.app/blog/2023/10/04/elevate-research-software-co-creating-a-digital-roadmap/

I need to make all links relative so that even in the previews, all links map to the current sandbox. But there you go.

**Comment by danielskatz** [comment]
I see - thanks

**Comment by danielskatz** [comment]
@karthik - will you be able to fix the relative link issue for the future?

**Comment by danielskatz** [comment]
@karthik - for multiple authors, we now use `author: "Eric A. Jensen and Daniel S. Katz"` - Is this correct syntax? Or should we do something else?

**Comment by danielskatz** [comment]
@karthik - finally, there's what looks like too much space after the header in this post and some other ones, before the main content starts, as below. Can this be adjusted? (no big deal either way...)

Screenshot 2023-10-05 at 08 37 02

**Comment by danielskatz** [comment]
@karthik - I'm going to go ahead and merge this, so that it's available for our workshop next week at eScience, but if you have thoughts on the issues I mentioned above, please let us know

**Comment by karthik** [comment]
I'll suggest an update for authors. They should be listed separately but this can be fixed later.

**Comment by karthik** [comment]
I'll try to fix the header spacing before I leave for the weekend.

**Pull request merged**
